version: 2.1
jobs:
  build-app:
    docker:
      - image: python:3.7.10
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements/common.txt" }}-{{ checksum "requirements/prod.txt" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.5.0/hadolint-Linux-x86_64 && \
            chmod +x /bin/hadolint
      - save_cache:
          paths:
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
          key: v1-dependencies-{{ checksum "requirements/common.txt" }}-{{ checksum "requirements/prod.txt" }}
      - run:
          name: Lint checks
          command: |
            hadolint Dockerfile
            pylint --disable=R,C,W1203 app.py
workflows:
  default:
    jobs:
      - build-app